export const BVHToSimpleMapping = {
  root: 'SpineBase',
  lowerback: 'SpineLow',
  upperback: 'SpineMid',
  thorax: '',
  neck: 'Neck',
  head: 'Head',
  lshoulderjoint: 'L_Shoulder',
  lhumerus: 'L_Arm',
  lradius: 'L_Forearm',
  lhand: 'L_HandBase',
  rshoulderjoint: 'R_Shoulder',
  rhumerus: 'R_Arm',
  rradius: 'R_Forearm',
  rhand: 'R_HandBase',
  rfemur: 'R_UpLeg',
  rtibia: 'R_Leg',
  rfoot: 'R_Foot',
  rtoes: 'R_Toe',
  lfemur: 'L_UpLeg',
  ltibia: 'L_Leg',
  lfoot: 'L_Foot',
  ltoes: 'L_Toe'
}
