export const CarnegieMellonUniversityToMixamoMapping = {
  hip: 'mixamorig_Hips',
  abdomen: 'mixamorig_Spine1',
  chest: 'mixamorig_Spine2',
  neck: 'mixamorig_Neck',
  head: 'mixamorig_Head',
  leftEye: '',
  rightEye: '',
  rCollar: '',
  lCollar: '',
  rShldr: 'mixamorig_RightShoulder',
  lShldr: 'mixamorig_LeftShoulder',
  rForeArm: 'mixamorig_RightForeArm',
  lForeArm: 'mixamorig_LeftForeArm',

  rHand: 'mixamorig_RightHand',
  lHand: 'mixamorig_LeftHand',
  rThumb1: 'mixamorig_RightHandThumb1',
  lThumb1: 'mixamorig_LeftHandThumb1',
  rThumb2: 'mixamorig_RightHandThumb2',
  lThumb2: 'mixamorig_LeftHandThumb2',
  rIndex1: 'mixamorig_RightHandIndex1',
  lIndex1: 'mixamorig_LeftHandIndex1',
  rIndex2: '',
  lIndex2: '',
  rMid1: 'mixamorig_RightHandMiddle1',
  lMid1: 'mixamorig_LeftHandMiddle1',
  rMid2: 'mixamorig_RightHandMiddle2',
  lMid2: ' mixamorig_LeftHandMiddle2',
  rRing1: 'mixamorig_RightHandRing1',
  lRing1: 'mixamorig_LeftHandRing1',
  rRing2: 'mixamorig_RightHandRing2',
  lRing2: 'mixamorig_LeftHandRing2',
  rPinky1: 'mixamorig_RightHandPinky1',
  lPinky1: 'mixamorig_LeftHandPinky1',

  rButtock: '',
  lButtock: '',
  rThigh: 'mixamorig_RightUpLeg',
  lThigh: 'mixamorig_LeftUpLeg',
  rShin: 'mixamorig_RightLeg',
  lShin: 'mixamorig_LeftLeg',
  rFoot: 'mixamorig_RightFoot',
  lFoot: 'mixamorig_LeftFoot'
}
